export const content = {
  pt: {
    label: "Português",
    nav: ["Aulas", "Metodologia", "Sobre", "Depoimentos"],
    cta: "Falar no Instagram",
    eyebrow: "Português, espanhol e inglês",
    heroTitle: ["Idiomas para a", "vida real."],
    heroLead: "Aulas online, leves e personalizadas com Isadora para você aprender com confiança e no seu ritmo.",
    heroPrimary: "Conhecer as aulas",
    heroSecondary: "Ver idiomas",
    online: "Aulas 100% online",
    personal: "Individual ou em grupo*",
    photoMain: "Foto principal da Isadora",
    photoAbout: "Foto da Isadora",
    photoNote: "foto a definir",
    floating: ["Aprender com", "leveza e intenção"],
    coursesKicker: "Escolha seu idioma",
    coursesTitle: "Um caminho para cada objetivo",
    coursesIntro: "Selecione um idioma para conhecer uma proposta inicial. Os detalhes finais serão definidos com Isadora.",
    levels: "Possibilidades de foco",
    courses: [
      { code: "PT", title: "Português", text: "Desenvolva conversação, escrita e compreensão com situações próximas da sua rotina.", detail: "Pronúncia, repertório, escrita e comunicação para objetivos pessoais ou profissionais." },
      { code: "ES", title: "Espanhol", text: "Ganhe repertório e confiança para se comunicar com mais naturalidade em diferentes contextos.", detail: "Conversação, compreensão oral, vocabulário e prática orientada para seus interesses." },
      { code: "EN", title: "Inglês", text: "Construa um percurso conectado aos seus interesses e pratique sem medo de errar.", detail: "Uso cotidiano, conversação, compreensão e um plano ajustado ao seu ritmo." },
    ],
    benefitsKicker: "Do seu jeito",
    benefitsTitle: "Uma experiência de aprendizagem feita para você",
    benefits: ["Aulas personalizadas", "Material adaptado", "Conversação na prática", "Ritmo flexível", "Acompanhamento próximo", "Situações do cotidiano"],
    methodKicker: "Como funciona",
    methodTitle: "Clareza para começar. Flexibilidade para continuar.",
    methodIntro: "Clique em cada etapa para conhecer uma proposta simples e ajustável.",
    steps: [
      ["01", "Primeira conversa", "Um encontro online para entender seu momento, interesses e o que você deseja desenvolver."],
      ["02", "Plano de estudos", "A proposta das aulas é organizada de acordo com sua rotina e suas prioridades."],
      ["03", "Aulas práticas", "Atividades variadas para usar o idioma em contextos claros e relevantes."],
      ["04", "Revisão contínua", "O percurso é acompanhado e ajustado conforme suas necessidades mudam."],
    ],
    aboutKicker: "Sobre Isadora",
    aboutTitle: "Ensinar uma língua é abrir espaço para novas conversas.",
    aboutText: ["Isadora é a professora por trás da Blá Blá Blando by Isaduera e oferece aulas online de português, espanhol e inglês.", "Este espaço pode receber depois a história, a metodologia e a trajetória profissional que ela desejar compartilhar."],
    aboutAccent: ["3 idiomas", "muitas possibilidades"],
    provisional: "Apresentação provisória",
    formatsKicker: "Formatos de aula",
    formatsTitle: "Aprenda do jeito que faz sentido para você",
    formatsIntro: "Selecione uma possibilidade para destacá-la.",
    formats: [["Individual", "Um percurso pensado inteiramente para seu ritmo e objetivo."], ["Em dupla", "Aprendizado compartilhado com atenção e espaço para praticar."], ["Grupo reduzido", "Trocas em grupo sem abrir mão de um acompanhamento próximo."], ["Foco específico", "Uma proposta personalizada para uma necessidade ou projeto."]],
    testimonialsKicker: "Depoimentos ilustrativos",
    testimonialsTitle: "Quem aprende, também conta a história",
    testimonials: [["Aluna A", "Português", "Texto provisório sobre uma experiência acolhedora e mais segurança para se comunicar."], ["Aluno B", "Inglês", "Texto provisório sobre uma metodologia leve e materiais conectados à rotina."], ["Estudante C", "Espanhol", "Texto provisório sobre aprender no próprio ritmo e praticar situações reais."]],
    contactKicker: "Vamos conversar?",
    contactTitle: "Seu próximo idioma pode começar com uma mensagem.",
    contactText: "Conheça o trabalho da Blá Blá Blando by Isaduera e converse diretamente com Isadora pelo Instagram.",
    instagram: "Abrir Instagram",
    footerTagline: "Aulas online de idiomas com proximidade, prática e propósito.",
    navigate: "Navegue",
    languages: "Idiomas",
    contact: "Contato",
    rights: "Informações provisórias para aprovação visual.",
    themeLight: "Ativar modo claro",
    themeDark: "Ativar modo escuro",
    languageControl: "Idioma do site",
    menu: "Abrir menu",
  },
  es: {
    label: "Español",
    nav: ["Clases", "Metodología", "Sobre mí", "Testimonios"],
    cta: "Hablar por Instagram",
    eyebrow: "Portugués, español e inglés",
    heroTitle: ["Idiomas para la", "vida real."],
    heroLead: "Clases online, ligeras y personalizadas con Isadora para que aprendas con confianza y a tu ritmo.",
    heroPrimary: "Conocer las clases",
    heroSecondary: "Ver idiomas",
    online: "Clases 100% online",
    personal: "Individual o en grupo*",
    photoMain: "Foto principal de Isadora",
    photoAbout: "Foto de Isadora",
    photoNote: "foto por definir",
    floating: ["Aprender con", "ligereza e intención"],
    coursesKicker: "Elige tu idioma",
    coursesTitle: "Un camino para cada objetivo",
    coursesIntro: "Selecciona un idioma para conocer una propuesta inicial. Los detalles finales se definirán con Isadora.",
    levels: "Posibilidades de enfoque",
    courses: [
      { code: "PT", title: "Portugués", text: "Desarrolla conversación, escritura y comprensión con situaciones cercanas a tu rutina.", detail: "Pronunciación, repertorio, escritura y comunicación para objetivos personales o profesionales." },
      { code: "ES", title: "Español", text: "Gana repertorio y confianza para comunicarte con naturalidad en diferentes contextos.", detail: "Conversación, comprensión oral, vocabulario y práctica orientada a tus intereses." },
      { code: "EN", title: "Inglés", text: "Construye un recorrido conectado a tus intereses y practica sin miedo a equivocarte.", detail: "Uso cotidiano, conversación, comprensión y un plan adaptado a tu ritmo." },
    ],
    benefitsKicker: "A tu manera",
    benefitsTitle: "Una experiencia de aprendizaje hecha para ti",
    benefits: ["Clases personalizadas", "Material adaptado", "Conversación práctica", "Ritmo flexible", "Acompañamiento cercano", "Situaciones cotidianas"],
    methodKicker: "Cómo funciona",
    methodTitle: "Claridad para empezar. Flexibilidad para continuar.",
    methodIntro: "Haz clic en cada etapa para conocer una propuesta sencilla y adaptable.",
    steps: [["01", "Primera conversación", "Un encuentro online para entender tu momento, intereses y objetivos."], ["02", "Plan de estudio", "Las clases se organizan de acuerdo con tu rutina y tus prioridades."], ["03", "Clases prácticas", "Actividades variadas para usar el idioma en contextos claros y relevantes."], ["04", "Revisión continua", "El recorrido se acompaña y ajusta según cambien tus necesidades."]],
    aboutKicker: "Sobre Isadora",
    aboutTitle: "Enseñar una lengua es abrir espacio para nuevas conversaciones.",
    aboutText: ["Isadora es la profesora detrás de Blá Blá Blando by Isaduera y ofrece clases online de portugués, español e inglés.", "Este espacio podrá recibir después la historia, la metodología y la trayectoria profesional que ella quiera compartir."],
    aboutAccent: ["3 idiomas", "muchas posibilidades"],
    provisional: "Presentación provisional",
    formatsKicker: "Formatos de clase",
    formatsTitle: "Aprende de la manera que tenga sentido para ti",
    formatsIntro: "Selecciona una posibilidad para destacarla.",
    formats: [["Individual", "Un recorrido pensado enteramente para tu ritmo y objetivo."], ["En pareja", "Aprendizaje compartido con atención y espacio para practicar."], ["Grupo reducido", "Intercambios en grupo con acompañamiento cercano."], ["Enfoque específico", "Una propuesta personalizada para una necesidad o proyecto."]],
    testimonialsKicker: "Testimonios ilustrativos",
    testimonialsTitle: "Quien aprende también cuenta la historia",
    testimonials: [["Alumna A", "Portugués", "Texto provisional sobre una experiencia acogedora y más seguridad al comunicarse."], ["Alumno B", "Inglés", "Texto provisional sobre una metodología ligera y materiales conectados con la rutina."], ["Estudiante C", "Español", "Texto provisional sobre aprender al propio ritmo y practicar situaciones reales."]],
    contactKicker: "¿Hablamos?",
    contactTitle: "Tu próximo idioma puede empezar con un mensaje.",
    contactText: "Conoce el trabajo de Blá Blá Blando by Isaduera y habla directamente con Isadora por Instagram.",
    instagram: "Abrir Instagram",
    footerTagline: "Clases online de idiomas con cercanía, práctica y propósito.",
    navigate: "Navega",
    languages: "Idiomas",
    contact: "Contacto",
    rights: "Información provisional para aprobación visual.",
    themeLight: "Activar modo claro",
    themeDark: "Activar modo oscuro",
    languageControl: "Idioma del sitio",
    menu: "Abrir menú",
  },
  en: {
    label: "English",
    nav: ["Classes", "Method", "About", "Testimonials"],
    cta: "Chat on Instagram",
    eyebrow: "Portuguese, Spanish and English",
    heroTitle: ["Languages for", "real life."],
    heroLead: "Friendly, personalized online lessons with Isadora so you can learn confidently and at your own pace.",
    heroPrimary: "Explore classes",
    heroSecondary: "View languages",
    online: "100% online classes",
    personal: "One-to-one or group*",
    photoMain: "Main photo of Isadora",
    photoAbout: "Photo of Isadora",
    photoNote: "photo to be defined",
    floating: ["Learn with", "ease and intention"],
    coursesKicker: "Choose your language",
    coursesTitle: "A path for every goal",
    coursesIntro: "Select a language to see an initial proposal. Final details will be defined with Isadora.",
    levels: "Possible areas of focus",
    courses: [
      { code: "PT", title: "Portuguese", text: "Develop speaking, writing and comprehension through situations connected to your routine.", detail: "Pronunciation, vocabulary, writing and communication for personal or professional goals." },
      { code: "ES", title: "Spanish", text: "Build vocabulary and confidence to communicate more naturally in different contexts.", detail: "Conversation, listening, vocabulary and practice guided by your interests." },
      { code: "EN", title: "English", text: "Build a learning path around your interests and practise without being afraid of mistakes.", detail: "Everyday use, conversation, comprehension and a plan adapted to your pace." },
    ],
    benefitsKicker: "Your way",
    benefitsTitle: "A learning experience made for you",
    benefits: ["Personalized lessons", "Adapted materials", "Practical conversation", "Flexible pace", "Close guidance", "Everyday situations"],
    methodKicker: "How it works",
    methodTitle: "Clarity to begin. Flexibility to continue.",
    methodIntro: "Click each step to explore a simple, adaptable approach.",
    steps: [["01", "First conversation", "An online meeting to understand your current level, interests and goals."], ["02", "Study plan", "Lessons are organized around your routine and priorities."], ["03", "Practical lessons", "Varied activities to use the language in clear, relevant contexts."], ["04", "Ongoing review", "Your learning path is followed and adjusted as your needs change."]],
    aboutKicker: "About Isadora",
    aboutTitle: "Teaching a language opens space for new conversations.",
    aboutText: ["Isadora is the teacher behind Blá Blá Blando by Isaduera and offers online Portuguese, Spanish and English lessons.", "This space can later share the story, teaching method and professional journey she chooses to present."],
    aboutAccent: ["3 languages", "many possibilities"],
    provisional: "Temporary introduction",
    formatsKicker: "Class formats",
    formatsTitle: "Learn in the way that makes sense for you",
    formatsIntro: "Select an option to highlight it.",
    formats: [["One-to-one", "A learning path designed entirely around your pace and goal."], ["In pairs", "Shared learning with attention and space to practise."], ["Small group", "Group exchange without losing close guidance."], ["Specific focus", "A personalized proposal for a particular need or project."]],
    testimonialsKicker: "Sample testimonials",
    testimonialsTitle: "Every learner has a story to tell",
    testimonials: [["Student A", "Portuguese", "Sample text about a welcoming experience and feeling more confident when communicating."], ["Student B", "English", "Sample text about a friendly method and materials connected to everyday life."], ["Student C", "Spanish", "Sample text about learning at their own pace and practising real situations."]],
    contactKicker: "Let's talk",
    contactTitle: "Your next language can begin with a message.",
    contactText: "Discover Blá Blá Blando by Isaduera and talk directly to Isadora on Instagram.",
    instagram: "Open Instagram",
    footerTagline: "Online language lessons with connection, practice and purpose.",
    navigate: "Navigate",
    languages: "Languages",
    contact: "Contact",
    rights: "Temporary information for visual approval.",
    themeLight: "Switch to light mode",
    themeDark: "Switch to dark mode",
    languageControl: "Website language",
    menu: "Open menu",
  },
};
